const fs = require('fs')
const path = require('path')

const files = [
  'src/services/messagingService/helpers.ts',
  'src/services/messagingService/templates/fusion-report.hbs',
  'src/services/messagingService/templates/fusion-review.hbs'
]

const replacements = [
  ['A curated view of potential matches and the scoring evidence behind them.', '{{i18n "curated_view"}}'],
  ['>Processing Statistics<', '>{{i18n "processing_statistics"}}<'],
  ['>Phase timing<', '>{{i18n "phase_timing"}}<'],
  ['>Aggregation Warnings<', '>{{i18n "aggregation_warnings"}}<'],
  ['>Aggregation Errors<', '>{{i18n "aggregation_errors"}}<'],
  ['>Fusion Review Decisions<', '>{{i18n "fusion_review_decisions"}}<'],
  ['>AUTO<', '>{{i18n "auto"}}<'],
  ['>Reviewer<', '>{{i18n "reviewer"}}<'],
  ['>Account<', '>{{i18n "account"}}<'],
  ['>Selected Identity<', '>{{i18n "selected_identity"}}<'],
  ['>Comments<', '>{{i18n "comments"}}<'],
  ['>New Fusion Reviews<', '>{{i18n "new_fusion_reviews"}}<'],
  ['>Source:<', '>{{i18n "source"}}<'],
  ['>Email:<', '>{{i18n "email"}}<'],
  ['>M<br>A<br>T<br>C<br>H<br>E<br>S<', '>{{{i18n "matches_vertical"}}}<'],
  ['>Error<', '>{{i18n "error"}}<'],
  ['>Exact<', '>{{i18n "exact"}}<'],
  ['>Deferred<', '>{{i18n "deferred"}}<'],
  ['>Attribute<', '>{{i18n "attribute"}}<'],
  ['>Algorithm<', '>{{i18n "algorithm"}}<'],
  ['>Threshold<', '>{{i18n "threshold"}}<'],
  ['>Value<', '>{{i18n "value"}}<'],
  ['>Score<', '>{{i18n "score"}}<'],
  ['>No match found<', '>{{i18n "no_match_found"}}<'],
  ['>No accounts included in this report.<', '>{{i18n "no_accounts_included"}}<'],
  ['>Identity Fusion Review Required<', '>{{i18n "review_required"}}<'],
  ['>Open Review Form<', '>{{i18n "open_review_form"}}<'],
  ['Please review the potential match and take appropriate action.', '{{i18n "please_review"}}'],
  ['This review was generated by the Identity Fusion NG Connector.', '{{i18n "generated_by"}}']
]

for (const file of files) {
  const p = path.join(process.cwd(), file)
  if (!fs.existsSync(p)) continue
  let content = fs.readFileSync(p, 'utf8')
  for (const [search, replace] of replacements) {
    content = content.split(search).join(replace)
  }
  fs.writeFileSync(p, content, 'utf8')
  console.log(`Updated ${file}`)
}
