export { MatchingService } from './matchingService'
export { ManagedAccountAnalyzer } from './managedAccountAnalyzer'
export { CandidateRegistry } from './candidateRegistry'
export { ManagedAccountMatchingRunner } from './managedAccountMatchingRunner'
export type { FusionMatch, ScoreReport } from './types'
export type { ManagedAccountAnalyzerState, ManagedAccountAnalysisContext } from './managedAccountAnalyzer'
export type { CandidateRegistryDeps } from './candidateRegistry'
export type { ManagedAccountMatchingRunnerState, ManagedAccountMatchingResult } from './managedAccountMatchingRunner'
export { MatchCandidateType } from './types'
